fixed race validation
RetroRabbit/RGO-Client pull request #524
Opened 2024-06-28 10:04 UTC by nzikalala

![image](https://github.com/RetroRabbit/RGO-Client/assets/172746187/05edfa1f-9a06-4d05-bb72-0bd3edc2913d)
![image](https://github.com/RetroRabbit/RGO-Client/assets/172746187/b0e53500-155c-4d56-a3bb-44ef190244fa)
![image](https://github.com/RetroRabbit/RGO-Client/assets/172746187/f40c1afa-2dba-4067-8a3e-c00380203461)
![image](https://github.com/RetroRabbit/RGO-Client/assets/172746187/e88707af-df7d-4e75-a9bf-8f06cdac2734)
![image](https://github.com/RetroRabbit/RGO-Client/assets/172746187/a19713c1-6f5f-41be-a84e-107c0068b9e8)

2024-06-28 10:10 UTC, MathildaShongwe15 approved these changes

2024-06-28 10:45 UTC, bseptember requested changes

2024-06-28 10:45 UTC, bseptember commented on src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
> +      this.personalFormProgress = Math.round((numberOfPopulatedFields / totalFields) * 100);
Exception:  Is there a scenario where totalFields can be equal to zero? If so, how are we handling this?

2024-06-28 10:45 UTC, bseptember commented on src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
> +          }
Refactor: the readability of this if statement could be improved perhaps with some whitespace before and after the brackets, and some new lines.

if (condition) {
   //some cool thing
}
else {
  //some other thing
}

2024-06-28 10:45 UTC, bseptember commented on src/app/components/hris/employees/employee-profile/shared-accordion-functionality.ts
> +
Refactor: We may not need this empty line here.

2024-07-01 07:28 UTC, EduanO submitted a review, later dismissed

2024-07-01 07:45 UTC, Juanro-Minne approved these changes

2024-07-01 08:03 UTC, madwizzard approved these changes

2024-07-01 08:04 UTC, Juanro-Minne approved these changes

2024-07-01 08:04 UTC, DewanAlberts approved these changes

2024-07-01 08:06 UTC, bseptember approved these changes

2024-07-01 08:07 UTC, merged