disability type added
RetroRabbit/RGO-Client pull request #537
Opened 2024-07-09 10:05 UTC by madwizzard

![Screenshot 2024-07-09 115935](https://github.com/RetroRabbit/RGO-Client/assets/82169901/05bbef36-2baf-4481-8e38-aee02b1b321b)
![Screenshot 2024-07-09 115942](https://github.com/RetroRabbit/RGO-Client/assets/82169901/354b6fa2-7afa-49f2-8e26-44916eafaf3c)
![Screenshot 2024-07-09 115949](https://github.com/RetroRabbit/RGO-Client/assets/82169901/7d23ec26-7832-44fb-9f4e-3ccae5849552)
![Screenshot 2024-07-09 120000](https://github.com/RetroRabbit/RGO-Client/assets/82169901/375eab99-4fb5-4812-88a7-0241d6488de6)
![Screenshot 2024-07-09 120004](https://github.com/RetroRabbit/RGO-Client/assets/82169901/306940bf-a387-4111-91a9-77719e8847c2)
![Screenshot 2024-07-09 120011](https://github.com/RetroRabbit/RGO-Client/assets/82169901/4ebe09fd-2f25-4af7-b789-6609ab20c751)

2024-07-09 11:14 UTC, MathildaShongwe15 approved these changes

2024-07-09 11:27 UTC, ReinoRabbit approved these changes

2024-07-09 17:10 UTC, EduanO requested changes

2024-07-09 17:10 UTC, EduanO commented on src/app/components/hris/employees/new-employee/new-employee.component.ts
> +    console.log(event)
```suggestion
```

2024-07-10 06:40 UTC, ZuenTheMan approved these changes

2024-07-10 06:41 UTC, ZuenTheMan approved these changes

2024-07-10 06:41 UTC, ReinoRabbit approved these changes

2024-07-10 06:42 UTC, EduanO approved these changes

2024-07-10 07:01 UTC, merged