DEV | Reduce the calls for filter-employees on the front end (employees tab)
RetroRabbit/RGO-Client pull request #621
Opened 2024-08-29 07:29 UTC by bseptember

### Overview

As per title

[ticket](https://dev.azure.com/retro-rabbit/HRIS/_sprints/taskboard/HRIS%20Team/HRIS/Sprint%2028?workitem=10302)

**BEFORE:**
![image](https://github.com/user-attachments/assets/54f3ae03-556c-4147-846b-8cd95c0c9d9d)

**AFTER:**
![image](https://github.com/user-attachments/assets/a82c6a91-c5db-4d49-9ad6-ef55a2129515)

2024-08-29 07:31 UTC, Wimmas submitted a review, later dismissed

2024-08-29 07:32 UTC, SuperSouls approved these changes, later dismissed

2024-08-29 11:22 UTC, madwizzard requested changes
filters for journey

2024-08-29 11:26 UTC, KAYEMBAJONATHAN approved these changes, later dismissed

2024-08-30 07:41 UTC, SuperSouls approved these changes

2024-08-30 11:41 UTC, madwizzard approved these changes

2024-08-30 11:50 UTC, MathildaShongwe15 approved these changes

2024-08-30 12:38 UTC, merged